"""Initial migration.

Revision ID: 61bf139edc6e
Revises: 
Create Date: 2026-03-12 23:07:02.269067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bf139edc6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_signature', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('stored_video_path', sa.String(length=1024), nullable=False),
    sa.Column('stored_thumbnail_path', sa.String(length=1024), nullable=False),
    sa.Column('video_title', sa.String(length=255), nullable=False),
    sa.Column('raw_ai_response', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_cache_video_signature'), ['video_signature'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('custom_title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_cache.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('highlight', sa.Boolean(), nullable=False),
    sa.Column('video_url', sa.String(length=2048), nullable=True),
    sa.Column('is_full_video', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_cache.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step')
    op.drop_table('recipe')
    op.drop_table('user')
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_cache_video_signature'))

    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
