"""Update models

Revision ID: 6b6af20bdfcc
Revises: 721f74f5e5b9
Create Date: 2026-03-14 00:28:38.331754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6af20bdfcc'
down_revision = '721f74f5e5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('file_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_video_resources_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_resources_original_url'), ['original_url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_resources_original_url'))
        batch_op.drop_index(batch_op.f('ix_video_resources_file_hash'))
        batch_op.drop_column('file_hash')
        batch_op.drop_column('original_url')

    # ### end Alembic commands ###
