"""Update models

Revision ID: 721f74f5e5b9
Revises: 61bf139edc6e
Create Date: 2026-03-14 00:22:46.824954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721f74f5e5b9'
down_revision = '61bf139edc6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('video_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_cache_video_signature'))

    op.drop_table('analysis_cache')
    op.drop_table('user')
    op.drop_table('step')
    op.drop_table('recipe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('analysis_id', sa.INTEGER(), nullable=False),
    sa.Column('custom_title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_cache.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('analysis_id', sa.INTEGER(), nullable=False),
    sa.Column('step_number', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.FLOAT(), nullable=False),
    sa.Column('end_time', sa.FLOAT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('highlight', sa.BOOLEAN(), nullable=False),
    sa.Column('video_url', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('is_full_video', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_cache.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('analysis_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('video_signature', sa.VARCHAR(length=255), nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('stored_video_path', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('stored_thumbnail_path', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('video_title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('raw_ai_response', sa.TEXT(), nullable=False),
    sa.Column('parser_version', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_cache_video_signature'), ['video_signature'], unique=1)

    op.drop_table('user_recipes')
    op.drop_table('recipe_steps')
    op.drop_table('video_resources')
    op.drop_table('users')
    # ### end Alembic commands ###
